services:
  server:
    image: amanelgau/excelant-develop:server-latest
    command: sh -c  "node ./build/src/server.js"
    ports:
      - 4040:4000
    environment:
      - DB_URI=mongodb://mongodb:27017/excelant
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.13
    volumes:
      - data/:/data/db
    ports:
      - 27017:27017
  web-client:
    image: amanelgau/excelant-develop:web-client-latest
    command: sh -c "npm run build"
    volumes:
      - web-client-build/:/web-client/build
    environment:
      - REACT_APP_BACK_URI=https://staging.remote3-0921.wns.wilders.dev/graphql
  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - web-client
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - data/:/data
      - web-client-build/:/web-client-build
      - ./logs:/var/log/nginx
volumes:
  web-client-build:
  data:
