name: docker-ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Check out code
        uses: actions/checkout@v2
      -
        name: Build and push
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: amanelgau/${{ secrets.DOCKER_HUB_PRODUCTION_IMAGE_NAME }}:server-latest
          context: ./server
      -
        name: Build and push
        id: docker_build_web_client
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: amanelgau/${{ secrets.DOCKER_HUB_PRODUCTION_IMAGE_NAME }}:web-client-latest
          context: ./web-client
