name: test-ci

on:
  pull_request

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto client and install dependencies
        run: cd web-client && npm ci
      # - name: Run ESLint
      #   run: eslint . --ext .js,.jsx,.ts,.tsx
      - name: Run Tests
        run: npm test
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto client and install dependencies
        run: cd server && npm ci 
      # - name: Run ESLint
      #   run: eslint . --ext .js,.jsx,.ts,.tsx
      - name: Run Tests
        run: npm test